---
version: "2"
run:
  timeout: 5m
issues:
  fix: true
linters:
  default: all
  settings:
    lll:
      line-length: 200
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
