project_name: aks-node-termination-handler
release:
  footer: |
    ## Docker Images
    - `paskalmaksim/{{.ProjectName}}:latest`
    - `paskalmaksim/{{.ProjectName}}:{{ .Tag }}`
builds:
- dir: ./cmd/
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X github.com/vince-riv/aks-node-termination-handler/pkg/config.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
