ARG WINDOWS_VERSION=ltsc2025@sha256:4bfc3ec32a8b9bb5e7a182440c517b0706267d88fda77b54acddf819920400ad

FROM mcr.microsoft.com/windows/nanoserver:$WINDOWS_VERSION

WORKDIR /app/

COPY ./aks-node-termination-handler.exe /app/aks-node-termination-handler.exe
USER ContainerUser

ENTRYPOINT [ "/app/aks-node-termination-handler.exe" ]
