ARG WINDOWS_VERSION=ltsc2025

FROM mcr.microsoft.com/windows/nanoserver:$WINDOWS_VERSION

WORKDIR /app/

COPY ./aks-node-termination-handler.exe /app/aks-node-termination-handler.exe
USER ContainerUser

ENTRYPOINT [ "/app/aks-node-termination-handler.exe" ]
