on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  validate-license:
    name: validate-license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - run: ./scripts/validate-license.sh